"""Foundational package for the Lua nil risk review agent."""

from .agent_driver_models import (
    AgentCapabilities,
    AgentProviderSpec,
)
from .agent_driver_manifest import (
    BUILTIN_AGENT_PROVIDER_MANIFESTS,
    BUILTIN_AGENT_PROVIDER_SPECS,
    build_agent_provider_manifest_template,
    CODEAGENT_PROVIDER_SPEC,
    CLAUDE_PROVIDER_SPEC,
    CODEX_PROVIDER_SPEC,
    GEMINI_PROVIDER_SPEC,
    get_builtin_agent_provider_manifest,
    get_builtin_agent_provider_spec,
    load_agent_provider_spec_manifest,
    load_agent_provider_spec_manifest_file,
)
from .agent_protocols import (
    CLI_PROTOCOL_BUILDERS,
    SchemaFileCliProtocol,
    StdoutEnvelopeCliProtocol,
    StdoutStructuredCliProtocol,
    get_cli_protocol_builder,
)
from .agent_backend import (
    AdjudicationBackend,
    AdjudicationBackendFactory,
    BackendError,
    build_manifest_backed_backend_factory,
    build_provider_spec_backed_backend_factory,
    CliAgentBackend,
    ClaudeCliBackend,
    CodeAgentCliBackend,
    CodexCliBackend,
    HeuristicAdjudicationBackend,
    create_adjudication_backend,
    get_cli_protocol_backend,
    get_adjudication_backend_factory,
    register_cli_protocol_backend,
    register_adjudication_backend,
    register_manifest_backed_adjudication_backend,
    unregister_adjudication_backend,
    unregister_cli_protocol_backend,
)
from .adjudication import adjudicate_packet
from .baseline import BaselineStore, build_baseline, filter_new_findings
from .cli import main, run
from .collector import collect_candidates
from .config_loader import ConfigError, load_confidence_policy, load_function_contracts, load_sink_rules
from .knowledge import (
    KnowledgeBase,
    derive_facts_from_contracts,
    derive_facts_from_summaries,
    facts_for_subject,
)
from .models import (
    AdjudicationRecord,
    AutofixPatch,
    BenchmarkCacheComparison,
    BenchmarkCaseResult,
    BenchmarkSummary,
    CandidateAssessment,
    CandidateCase,
    ConfidencePolicy,
    EvidencePacket,
    EvidenceTarget,
    RepositorySnapshot,
    FunctionContract,
    FunctionSummary,
    KnowledgeFact,
    RoleOpinion,
    SinkRule,
    StaticProof,
    StaticAnalysisResult,
    Verdict,
    VerificationSummary,
    with_candidate_state,
)
from .pipeline import build_evidence_packet, should_report
from .parser_backend import collect_call_sites, get_parser_backend_info
from .prompting import build_adjudication_prompt
from .reporting import render_json_report, render_markdown_report
from .repository import discover_lua_files
from .skill_runtime import (
    ADJUDICATOR_SKILL_CONTRACT,
    SkillDefinition,
    SkillRuntimeError,
    compile_adjudicator_skill_header,
    default_adjudicator_skill_path,
    fallback_adjudicator_skill_header,
    load_adjudicator_skill,
    load_skill_definition,
)
from .service import (
    apply_autofix_manifest,
    benchmark_repository_review,
    benchmark_cache_compare,
    bootstrap_repository,
    clear_backend_cache,
    export_adjudication_tasks,
    export_autofix_patches,
    export_autofix_unified_diff,
    find_repository_root_for_file,
    refresh_knowledge_base,
    prepare_evidence_packet,
    refresh_summary_cache,
    review_repository_file,
    review_repository,
    run_file_review,
    run_repository_review,
    review_source,
)
from .summaries import SummaryStore, summarize_source
from .static_analysis import analyze_candidate
from .verification import verify_verdict

__all__ = [
    "AdjudicationRecord",
    "AdjudicationBackend",
    "AdjudicationBackendFactory",
    "ADJUDICATOR_SKILL_CONTRACT",
    "AgentCapabilities",
    "AgentProviderSpec",
    "AutofixPatch",
    "BackendError",
    "BenchmarkCacheComparison",
    "BenchmarkCaseResult",
    "BenchmarkSummary",
    "BaselineStore",
    "CliAgentBackend",
    "CLI_PROTOCOL_BUILDERS",
    "CandidateAssessment",
    "CandidateCase",
    "ConfidencePolicy",
    "ConfigError",
    "BUILTIN_AGENT_PROVIDER_SPECS",
    "BUILTIN_AGENT_PROVIDER_MANIFESTS",
    "build_agent_provider_manifest_template",
    "CODEAGENT_PROVIDER_SPEC",
    "CLAUDE_PROVIDER_SPEC",
    "ClaudeCliBackend",
    "CodeAgentCliBackend",
    "CODEX_PROVIDER_SPEC",
    "GEMINI_PROVIDER_SPEC",
    "EvidencePacket",
    "EvidenceTarget",
    "FunctionContract",
    "FunctionSummary",
    "KnowledgeBase",
    "KnowledgeFact",
    "CodexCliBackend",
    "HeuristicAdjudicationBackend",
    "RoleOpinion",
    "RepositorySnapshot",
    "SchemaFileCliProtocol",
    "SinkRule",
    "SkillDefinition",
    "SkillRuntimeError",
    "StdoutEnvelopeCliProtocol",
    "StdoutStructuredCliProtocol",
    "SummaryStore",
    "StaticAnalysisResult",
    "StaticProof",
    "Verdict",
    "VerificationSummary",
    "with_candidate_state",
    "adjudicate_packet",
    "apply_autofix_manifest",
    "benchmark_repository_review",
    "benchmark_cache_compare",
    "bootstrap_repository",
    "build_baseline",
    "build_adjudication_prompt",
    "build_manifest_backed_backend_factory",
    "build_provider_spec_backed_backend_factory",
    "build_evidence_packet",
    "clear_backend_cache",
    "collect_candidates",
    "collect_call_sites",
    "create_adjudication_backend",
    "discover_lua_files",
    "compile_adjudicator_skill_header",
    "default_adjudicator_skill_path",
    "derive_facts_from_summaries",
    "derive_facts_from_contracts",
    "export_adjudication_tasks",
    "export_autofix_patches",
    "export_autofix_unified_diff",
    "find_repository_root_for_file",
    "fallback_adjudicator_skill_header",
    "facts_for_subject",
    "filter_new_findings",
    "get_adjudication_backend_factory",
    "get_builtin_agent_provider_manifest",
    "get_builtin_agent_provider_spec",
    "get_cli_protocol_backend",
    "get_cli_protocol_builder",
    "load_confidence_policy",
    "load_function_contracts",
    "load_adjudicator_skill",
    "load_sink_rules",
    "load_skill_definition",
    "main",
    "load_agent_provider_spec_manifest",
    "load_agent_provider_spec_manifest_file",
    "analyze_candidate",
    "get_parser_backend_info",
    "summarize_source",
    "prepare_evidence_packet",
    "refresh_knowledge_base",
    "refresh_summary_cache",
    "register_cli_protocol_backend",
    "review_repository_file",
    "review_repository",
    "render_json_report",
    "render_markdown_report",
    "register_adjudication_backend",
    "register_manifest_backed_adjudication_backend",
    "run",
    "run_file_review",
    "run_repository_review",
    "review_source",
    "should_report",
    "unregister_adjudication_backend",
    "unregister_cli_protocol_backend",
    "verify_verdict",
]
